### ISSUE TITLE
Splitting enchanted books

### ISSUE THREAD

**Issue by ejm554** [H7KZ/Disenchantment#11]
I'd like to suggest an _Disenchantment enhancement._

Your plugin allows me to remove and save enchantments from tools, weapons, and armor. Could you provide a feature that will allow players to 'split' enchantments from a _book_ that has multiple enchantments, and 'transfer' them to a new book?

I often acquire items from mobs that are enchanted with multiple items. I love how your tool will allows me to put these enchantments into a single book. But I often don't want or like the specific combination of enchantments. It would be great if I could also put one of these enchanted books into an anvil, along with a regular book, and 'transfer' the enchantment.

**Comment by H7KZ** [comment]
Sounds pretty interesting! Will take a look at implementing this feature!

**Comment by H7KZ** [comment]
https://github.com/H7KZ/Disenchantment/releases/tag/v5.2.0
