### ISSUE TITLE
Commands all work but can't disenchant

### ISSUE THREAD

**Issue by iiTej** [H7KZ/Disenchantment#3]
My server is on Paper 1.20.2 and it shows all the help commands and they all function like normal and I gave myself permissions to use but still can't get it to actually function in an anvil.

**Comment by H7KZ** [comment]
Could you elaborate more please? Although I found a small mistake in my code tho, that I do not check any permission in the actual anvil event, I will be pushing a new version for this in few minutes. There is going to be a new permission "disenchantment.anvil" to be able to use the anvil.

**Comment by iiTej** [comment]
I gave myself every permission including the anvil permission and typed in
disench.toggle and it is switched to enabled. I put a golden pickaxe with
Fortune 2 in an anvil and a book in the second spot and it just gives me an
X

**Comment by H7KZ** [comment]
Could you please list if you have any other plugins that do something with the anvil? This type of behaviour isn't happening on my version 1.20.2 Paper. Thanks

**Comment by iiTej** [comment]
The only plugins I have are: Disenchantment, Homes, AutoTreeChop, Simple
Tpa, ViaVersion, Longer Days, and MyPermissions. Nothing that does
with anvil I believe

**Comment by iiTej** [comment]
2023-12-28 00-50-42.mkv
<https://drive.google.com/file/d/1l4LZCj1kp0xPHv-4yn5o3bprz2TtEZK3/view?usp=drive_web>

**Comment by H7KZ** [comment]
Could you please make it public? Thank you :)

**Comment by iiTej** [comment]
Done.

**Comment by H7KZ** [comment]
interesting behaviour, could you also assign permission "disenchantment.anvil" to yourself? Then I would really need to dig in why this is happening, nothing to console? No error logs? No output? I am sorry if I am costing your time like this but I really wanna go to the bottom of it so no one else has this similar problem :( Thanks a lot!

**Comment by iiTej** [comment]
2023-12-28 16-12-02.mkv
<https://drive.google.com/file/d/1_hJaP3solKO8j4PPklhKTs5m5yW_BCuK/view?usp=drive_web>
Absolutely nothing goes to console, no crash report, absolutely nothing.

**Comment by H7KZ** [comment]
The hell... I don't know man :/ I tried on my PC, Paper 1.20.2, deop myself, luckperms group with only the disenchantment.anvil permission and I am able to use it. When I removed the permission I couldn't disenchant, so for me the behaviour is correct, but in your case I really don't have a clue :////

Well... I have no fckin idea.

**Comment by iiTej** [comment]
I just figured out the issue. Its something with Bedrock Edition. On both
my xbox and my girlfriends it won't work. I connected on my Java Edition
and it works just fine. So apparently thats the issue.

**Comment by H7KZ** [comment]
Oh wow :D That explains it a bit, good to know! Glad you found out why it is happening :)
