### ISSUE TITLE
Add 1.20.6 Support

### ISSUE THREAD

**Issue by Raidware** [H7KZ/Disenchantment#6]
Add 1.20.6 Support. Also 1.21 will be releasing.

**Comment by Raidware** [comment]
@H7KZ

**Comment by H7KZ** [comment]
should be done... or I hope so :D Sorry that I don't have much time to contribute :(

**Comment by ejm554** [comment]
I'd like to clarify which version(s) of the plugin are compatible with Minecraft (Paper) 1.20.6. Can I use a plugin version that is _above_ 3.0.0, or is that the highest version possible?

I verified that version 3.0.0 is compatible, whereas attempting to use version 5.1.0 results the server logging an error:

`22 ... Could not load plugin 'Disenchantment-5.1.0.jar' in folder 'plugins/.paper-remapped'`

Complete log here: https://mclo.gs/NAKCy4S

**Comment by H7KZ** [comment]
https://github.com/H7KZ/Disenchantment/releases/tag/v5.1.1
