### ISSUE TITLE
Disenchanting "corrupts" items

### ISSUE THREAD

**Issue by Chronic667** [H7KZ/Disenchantment#7]
Plugin Version - Disenchantment-3.0.0 
Minecraft Version - 1.21
Server Version - "CraftBukkit version 4261-Spigot-491f367-aceddcd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)

When disenchanting an item the item can no longer be enchanted, effectively corrupting the item.

**Comment by H7KZ** [comment]
Looking into it, expect fix by tomorrow hopefully. Weird behaviour... testing it :/

**Comment by H7KZ** [comment]
Fixed in this commit https://github.com/H7KZ/Disenchantment/commit/11b91daeadbb99dda290cb0dea09d7f77bd2aaef
