### ISSUE TITLE
Issue with disenchanting

### ISSUE THREAD

**Issue by FearlessNite345** [H7KZ/Disenchantment#9]
I have given myself the "disenchantment.anvil" perm and im on 1.21 PaperMC when i try to place a item in the anvil with the book it flickers for one second in the output then goes away and i have not been able to track down any errors i can find i do use EcoEnchants if maybe its a issue with that

**Comment by FearlessNite345** [comment]
Here is a video of said issue https://youtu.be/bw2bcJcuHTA

**Comment by FearlessNite345** [comment]
Still guessing the issue is with EcoEnchants as i see you now added the warning back to the spigot page after you said it would work with it now

**Comment by H7KZ** [comment]
Yeah idk, will look into it when I have time. If you need it right away, you can open up a MR with fixes :D Otherwise wait, don't have much time

**Comment by H7KZ** [comment]
Would you please also include any console logs from the event? If there isn't some sort of easy explanation? I am currently on vacation and will be coming back in 2 days. Then I can really look into it. But there is problem with testing it really well... Eco is monetized, but is open-sourced and well... I only gave it a few minutes to try to compile but hell... there were some deps issues so I really didn't think about it :D I believed that it would work (of course it didn't -_- :DDD)

**Comment by FearlessNite345** [comment]
So i have made a Fork of this repo and tried to play around with it to see if anything will work and i did come across that EcoEnchants handles the same anvil event and im wondering if its almost overriding yours ive not been able to get any errors or anything as i dont really think its a error i think its just EcoEnchants settings the anvil output to nothing nearly instant maybe im wrong but it would make since how it makes the book but then disappears

**Comment by FearlessNite345** [comment]
https://github.com/Auxilor/EcoEnchants/blob/master/eco-core/core-plugin/src/main/kotlin/com/willfp/ecoenchants/mechanics/AnvilSupport.kt

**Comment by FearlessNite345** [comment]
if needed i could send you my version of it just so you can test cause it does make it harder without having it

**Comment by H7KZ** [comment]
> if needed i could send you my version of it just so you can test cause it does make it harder without having it

that would be absolutely amazing! :D

**Comment by FearlessNite345** [comment]
Question do you have discord so i don't post it here and make it public for everyone

**Comment by H7KZ** [comment]
h7kz

**Comment by H7KZ** [comment]
Waiting for EcoEnchants to merge PR, otherwise this is marked as closed

https://github.com/Auxilor/EcoEnchants/pull/397
